package ch.heigvd;



public class Description {
    public static final String DESCRIPTION = """
                                 
                      .----------------.  .-----------------. .----------------.  .----------------.
                     | .--------------. || .--------------. || .--------------. || .--------------. |
                     | |     _____    | || | ____  _____  | || |  ___  ____   | || |     ____     | |
                     | |    |_   _|   | || ||_   \\|_   _| | || | |_  ||_  _|  | || |   .'    `.   | |
                     | |      | |     | || |  |   \\ | |   | || |   | |_/ /    | || |  /  .--.  \\  | |
                     | |      | |     | || |  | |\\ \\| |   | || |   |  __'.    | || |  | |    | |  | |
                     | |     _| |_    | || | _| |_\\   |_  | || |  _| |  \\ \\_  | || |  \\  `--'  /  | |
                     | |    |_____|   | || ||_____|\\____| | || | |____||____| | || |   `.____.'   | |
                     | |              | || |              | || |              | || |              | |
                     | '--------------' || '--------------' || '--------------' || '--------------' |
                      '----------------'  '----------------'  '----------------'  '----------------'
                                 
                                 
                                Inko lets you write custom text or exif values on an image
                                
                                  Follow me on Github : https://github.com/AlexandreIorio
                                 
                        
                                                          10.2023
                        
                        
                                                Performed by Alexandre Iorio 
                             during the DAI course at HEIG-VD in Yverdon-les-Bains Switzerland
                                given by Ludovic Delafontaine - https://github.com/ludelafo 
                               and assisted by Hadrien Louis - https://github.com/hadrylouis
                               
                               
                    ---------------------------------------------------------------------------------
                                                        LIBRARIES
                    ---------------------------------------------------------------------------------
                               
            Logo generated by with https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
                               
                               Exif reading with  https://github.com/drewnoakes/metadata-extractor
                               
                                               CLI with https://picocli.info/
                                 
                     ---------------------------------------------------------------------------------
                     """;

    }
